/* global React, Icon, StatusPill, Btn, Modal, Banner, relativeTime, fmtDate */

function WorkspacesPage({ sessions, onOpen, onCreate }) {
  const [createOpen, setCreateOpen] = React.useState(false);
  return (
    <div className="col" style={{ gap: 14 }}>
      <div className="filter-bar">
        <div className="input-icon">
          <Icon name="search" size={13} className="icon" />
          <input className="input" placeholder="Filter workspaces…" />
        </div>
        <div className="sep-v" />
        <select className="select"><option>all templates</option></select>
        <select className="select"><option>all providers</option></select>
        <div style={{ marginLeft: "auto" }}>
          <Btn size="sm" kind="primary" icon="plus" onClick={() => setCreateOpen(true)}>New workspace</Btn>
        </div>
      </div>

      <div className="tbl-wrap">
        <table className="tbl">
          <thead>
            <tr>
              <th>ID</th>
              <th>Template</th>
              <th>Provider</th>
              <th style={{ textAlign: "right" }}>Sessions</th>
              <th>Created</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {window.MOCK.WORKSPACES.map((wid) => {
              const d = window.MOCK.WORKSPACE_DETAILS[wid];
              const onWs = sessions.filter((s) => s.workspace_id === wid && !["ended", "failed", "cancelled"].includes(s.status));
              return (
                <tr key={wid} onClick={() => onOpen(wid)}>
                  <td className="mono">{wid}</td>
                  <td className="mono">{d.template}</td>
                  <td>
                    <ProviderBadge kind={d.provider} />
                  </td>
                  <td className="mono num tabular">
                    {onWs.length > 0 ? (
                      <span style={{ color: "var(--blue)" }}>{onWs.length}</span>
                    ) : (
                      <span className="muted">0</span>
                    )}
                  </td>
                  <td className="mono muted">{relativeTime(d.created_at_ago / 1000)}</td>
                  <td style={{ textAlign: "right", paddingRight: 12 }}>
                    <Icon name="chevron-right" size={12} className="muted" />
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      {createOpen && (
        <Modal
          title="New workspace"
          onClose={() => setCreateOpen(false)}
          footer={
            <>
              <Btn kind="ghost" onClick={() => setCreateOpen(false)}>Cancel</Btn>
              <Btn kind="primary" icon="plus" onClick={() => { setCreateOpen(false); onCreate && onCreate(); }}>Create</Btn>
            </>
          }
        >
          <div className="field">
            <label className="field-label">Template</label>
            <select className="select" style={{ width: "100%" }}>
              <option>python-3.11-slim</option>
              <option>node-22</option>
              <option>stripe-toolkit</option>
            </select>
          </div>
          <div className="field">
            <label className="field-label">Overrides <span className="hint">optional</span></label>
            <textarea className="textarea mono" placeholder="env.MY_KEY=value&#10;init_commands += apt install jq" rows={3} />
          </div>
          <div className="banner banner-info" style={{ margin: 0, fontSize: 11.5 }}>
            <Icon name="info" size={12} className="ico" />
            <div>ID is generated by the backend — any <span className="mono">id</span> field in this body is silently ignored (spec §12).</div>
          </div>
        </Modal>
      )}
    </div>
  );
}

function ProviderBadge({ kind }) {
  const map = {
    local: { label: "local", color: "var(--text-2)" },
    container: { label: "container", color: "var(--blue)" },
    k8s: { label: "k8s", color: "var(--violet)" },
  };
  const m = map[kind] || map.local;
  return (
    <span className="pill" style={{ background: "var(--bg-2)", color: m.color, border: "1px solid var(--border)" }}>
      <span className="dot" style={{ background: m.color }}></span>
      {m.label}
    </span>
  );
}

// ----------------------------------------------------------------------
// Detail
// ----------------------------------------------------------------------

function WorkspaceDetail({ workspaceId, sessions, onBack, onOpenSession, onNavigate, pushToast }) {
  const [tab, setTab] = React.useState("files");
  const [destroyOpen, setDestroyOpen] = React.useState(false);
  const d = window.MOCK.WORKSPACE_DETAILS[workspaceId] || { template: "(unknown)", provider: "container", created_at_ago: 0 };
  const wsSessions = sessions.filter((s) => s.workspace_id === workspaceId);

  return (
    <div className="col" style={{ gap: 14 }}>
      {/* Tabbed top */}
      <div className="panel">
        <div style={{ display: "flex", alignItems: "center", borderBottom: "1px solid var(--border)", padding: "0 12px" }}>
          {[
            { id: "files", label: "Files", icon: "doc" },
            { id: "sessions", label: "Sessions", icon: "zap", count: wsSessions.length },
            { id: "log", label: "Log", icon: "git-commit" },
            { id: "channels", label: "Channels", icon: "bell" },
            { id: "config", label: "Config", icon: "settings" },
            { id: "destroy", label: "Destroy", icon: "trash", danger: true },
          ].map((t) => (
            <button
              key={t.id}
              onClick={() => setTab(t.id)}
              style={{
                background: "none",
                border: "none",
                padding: "10px 14px",
                cursor: "pointer",
                color: tab === t.id ? "var(--text)" : "var(--text-3)",
                fontSize: 12.5,
                fontWeight: tab === t.id ? 600 : 400,
                borderBottom: tab === t.id ? "2px solid var(--accent)" : "2px solid transparent",
                marginBottom: -1,
                display: "inline-flex",
                alignItems: "center",
                gap: 6,
              }}
            >
              <Icon name={t.icon} size={13} style={{ color: t.danger ? "var(--red)" : undefined }} />
              {t.label}
              {t.count != null && t.count > 0 && (
                <span className="count" style={{ marginLeft: 4 }}>{t.count}</span>
              )}
            </button>
          ))}
        </div>
        <div className="panel-body" style={{ padding: 0 }}>
          {tab === "files" && <FilesTab pushToast={pushToast} />}
          {tab === "sessions" && <SessionsTab sessions={wsSessions} onOpen={onOpenSession} />}
          {tab === "log" && <LogTab />}
          {tab === "channels" && <ChannelsTab workspaceId={workspaceId} pushToast={pushToast} onNavigate={onNavigate} />}
          {tab === "config" && <ConfigTab workspaceId={workspaceId} detail={d} />}
          {tab === "destroy" && <DestroyTab workspaceId={workspaceId} wsSessions={wsSessions} onOpen={() => setDestroyOpen(true)} />}
        </div>
      </div>

      {destroyOpen && (
        <Modal
          title={`Destroy ${workspaceId}?`}
          danger
          onClose={() => setDestroyOpen(false)}
          footer={
            <>
              <Btn kind="ghost" onClick={() => setDestroyOpen(false)}>Cancel</Btn>
              <Btn kind="danger" icon="trash" onClick={() => { setDestroyOpen(false); pushToast({ kind: "warning", title: "Destroying workspace", detail: `${wsSessions.filter((s) => !["ended","failed","cancelled"].includes(s.status)).length} sessions will be cancelled first.` }); }}>
                Destroy permanently
              </Btn>
            </>
          }
        >
          <ul>
            <li><strong>{wsSessions.filter((s) => !["ended","failed","cancelled"].includes(s.status)).length}</strong> active session(s) on this workspace will be <strong>cancelled before destroy</strong>.</li>
            <li>The <span className="mono">.state</span> git repo will be deleted <strong>permanently</strong> — turn history will be gone.</li>
            <li>Any files written by sessions are removed.</li>
            <li>This cannot be undone.</li>
          </ul>
        </Modal>
      )}
    </div>
  );
}

// ----- Files tab ------

function FilesTab({ pushToast }) {
  const [openDirs, setOpenDirs] = React.useState(() => new Set(["/", "/src"]));
  const [selected, setSelected] = React.useState("/src/main.py");
  const [editing, setEditing] = React.useState(false);
  const [content, setContent] = React.useState(() => window.MOCK.FILE_PREVIEWS[selected] || "");

  const toggleDir = (path) => {
    const next = new Set(openDirs);
    if (next.has(path)) next.delete(path); else next.add(path);
    setOpenDirs(next);
  };

  const selectFile = (path) => {
    setSelected(path);
    setEditing(false);
    setContent(window.MOCK.FILE_PREVIEWS[path] || `// Binary or unsupported preview\n// ${path}\n// ${(window.MOCK.FILE_TREE[path] || {}).size || 0} bytes`);
  };

  return (
    <div style={{ display: "grid", gridTemplateColumns: "300px 1fr", minHeight: 480, fontSize: 12.5 }}>
      {/* Tree */}
      <div style={{ borderRight: "1px solid var(--border)", overflow: "auto", padding: "10px 0" }}>
        <div style={{ display: "flex", alignItems: "center", padding: "0 12px 8px", gap: 6 }}>
          <span className="mono muted text-sm">/ root</span>
          <div style={{ marginLeft: "auto", display: "flex", gap: 4 }}>
            <button className="icon-btn" style={{ width: 22, height: 22 }} title="New file"><Icon name="plus" size={10} /></button>
            <button className="icon-btn" style={{ width: 22, height: 22 }} title="Refresh"><Icon name="refresh" size={10} /></button>
          </div>
        </div>
        <DirNode path="/" depth={0} openDirs={openDirs} toggleDir={toggleDir} selected={selected} selectFile={selectFile} />
      </div>

      {/* Editor pane */}
      <div style={{ display: "flex", flexDirection: "column", overflow: "hidden", minWidth: 0 }}>
        <div style={{ display: "flex", alignItems: "center", padding: "8px 12px", borderBottom: "1px solid var(--border)", gap: 8 }}>
          <Icon name="doc" size={12} className="muted" />
          <span className="mono" style={{ fontSize: 12 }}>{selected}</span>
          <span className="muted mono text-sm">· {(window.MOCK.FILE_TREE[selected] || {}).size || 0} bytes</span>
          <div style={{ marginLeft: "auto", display: "flex", gap: 6 }}>
            {editing ? (
              <>
                <Btn size="sm" kind="ghost" onClick={() => { setEditing(false); setContent(window.MOCK.FILE_PREVIEWS[selected] || ""); }}>Discard</Btn>
                <Btn size="sm" kind="primary" icon="check" onClick={() => { setEditing(false); pushToast({ kind: "success", title: "Saved", detail: `PUT ${selected} → 200` }); }}>Save</Btn>
              </>
            ) : (
              <>
                <Btn size="sm" kind="ghost" icon="external">Download</Btn>
                <Btn size="sm" kind="ghost" icon="copy" onClick={() => setEditing(true)}>Edit</Btn>
              </>
            )}
          </div>
        </div>
        <div style={{ flex: 1, overflow: "auto", background: "var(--bg)" }}>
          {editing ? (
            <textarea
              className="textarea mono"
              style={{ width: "100%", border: 0, borderRadius: 0, height: "100%", minHeight: 400, background: "var(--bg)", fontSize: 12, lineHeight: 1.55, padding: 14 }}
              value={content}
              onChange={(e) => setContent(e.target.value)}
            />
          ) : (
            <pre className="mono" style={{ margin: 0, padding: 14, fontSize: 12, lineHeight: 1.55, color: "var(--text-2)", whiteSpace: "pre-wrap" }}>
              <CodeHighlight code={content} lang={(window.MOCK.FILE_TREE[selected] || {}).lang} />
            </pre>
          )}
        </div>
      </div>
    </div>
  );
}

function DirNode({ path, depth, openDirs, toggleDir, selected, selectFile }) {
  const dir = window.MOCK.FILE_TREE[path];
  if (!dir) return null;
  const open = openDirs.has(path);
  const children = dir.children || [];
  // Render children sorted: dirs first
  const sortedChildren = [...children].sort((a, b) => {
    const pa = (path === "/" ? "/" : path + "/") + a;
    const pb = (path === "/" ? "/" : path + "/") + b;
    const isDirA = (window.MOCK.FILE_TREE[pa] || {}).type === "dir";
    const isDirB = (window.MOCK.FILE_TREE[pb] || {}).type === "dir";
    if (isDirA && !isDirB) return -1;
    if (!isDirA && isDirB) return 1;
    // System files (.state, .tmp) to the bottom
    const aSys = a.startsWith(".");
    const bSys = b.startsWith(".");
    if (aSys && !bSys) return 1;
    if (!aSys && bSys) return -1;
    return a.localeCompare(b);
  });
  return (
    <div>
      {path !== "/" && (
        <FileRow
          path={path}
          name={path.split("/").pop()}
          isDir
          open={open}
          depth={depth - 1}
          system={dir.system}
          onClick={() => toggleDir(path)}
        />
      )}
      {(path === "/" || open) &&
        sortedChildren.map((childName) => {
          const childPath = (path === "/" ? "/" : path + "/") + childName;
          const child = window.MOCK.FILE_TREE[childPath];
          if (!child) return null;
          if (child.type === "dir") {
            return (
              <DirNode
                key={childPath}
                path={childPath}
                depth={depth + 1}
                openDirs={openDirs}
                toggleDir={toggleDir}
                selected={selected}
                selectFile={selectFile}
              />
            );
          }
          return (
            <FileRow
              key={childPath}
              path={childPath}
              name={childName}
              depth={depth}
              isSelected={childPath === selected}
              onClick={() => selectFile(childPath)}
              size={child.size}
              system={childPath.startsWith("/.state") || childPath.startsWith("/.tmp")}
            />
          );
        })}
    </div>
  );
}

function FileRow({ name, depth, isDir, open, isSelected, system, onClick, size }) {
  return (
    <div
      onClick={onClick}
      style={{
        display: "flex",
        alignItems: "center",
        gap: 5,
        padding: "3px 12px",
        paddingLeft: 12 + depth * 14,
        cursor: "pointer",
        background: isSelected ? "var(--accent-dim)" : undefined,
        color: system ? "var(--text-4)" : isSelected ? "var(--text)" : "var(--text-2)",
        fontSize: 12.5,
      }}
      title={system ? "backend-managed; do not edit directly" : undefined}
      onMouseEnter={(e) => { if (!isSelected) e.currentTarget.style.background = "var(--bg-hover)"; }}
      onMouseLeave={(e) => { if (!isSelected) e.currentTarget.style.background = "transparent"; }}
    >
      {isDir ? (
        <>
          <Icon name={open ? "chevron-down" : "chevron-right"} size={10} className="muted" />
          <Icon name="box" size={12} style={{ color: "var(--text-3)" }} />
        </>
      ) : (
        <>
          <span style={{ width: 10 }} />
          <Icon name="doc" size={11} style={{ color: "var(--text-4)" }} />
        </>
      )}
      <span className="mono" style={{ fontSize: 12 }}>{name}</span>
      {!isDir && size != null && (
        <span className="muted mono text-sm" style={{ marginLeft: "auto", fontSize: 10.5 }}>
          {size === 0 ? "0" : size < 1024 ? `${size}B` : `${(size / 1024).toFixed(1)}K`}
        </span>
      )}
    </div>
  );
}

function CodeHighlight({ code, lang }) {
  // Very simple highlight (keywords, strings, numbers, comments)
  const lines = (code || "").split("\n");
  const isPy = lang === "python";
  const kw = /\b(import|from|def|class|return|if|else|elif|async|await|yield|in|not|and|or|with|as|for|while|try|except|finally|raise|pass|None|True|False)\b/g;
  return (
    <>
      {lines.map((line, i) => {
        let html = line
          .replace(/&/g, "&amp;")
          .replace(/</g, "&lt;")
          .replace(/>/g, "&gt;");
        // comments
        html = html.replace(/(#.*$)/g, '<span style="color:var(--text-4);font-style:italic">$1</span>');
        // strings
        html = html.replace(/(""".*?"""|".*?"|'.*?')/g, '<span style="color:var(--green)">$1</span>');
        // numbers
        html = html.replace(/\b(\d+(?:\.\d+)?)\b/g, '<span style="color:var(--amber)">$1</span>');
        if (isPy) {
          html = html.replace(kw, '<span style="color:var(--violet)">$1</span>');
        }
        return (
          <div key={i} style={{ display: "flex" }}>
            <span style={{ width: 36, color: "var(--text-4)", textAlign: "right", paddingRight: 12, userSelect: "none", flexShrink: 0 }}>{i + 1}</span>
            <span dangerouslySetInnerHTML={{ __html: html || "&nbsp;" }} />
          </div>
        );
      })}
    </>
  );
}

// ----- Sessions tab ------

function SessionsTab({ sessions, onOpen }) {
  return (
    <div style={{ padding: 14 }}>
      <div style={{ display: "flex", alignItems: "center", marginBottom: 10 }}>
        <div>
          <div className="text-sm muted">Sessions running on this workspace</div>
        </div>
        <div style={{ marginLeft: "auto" }}>
          <Btn size="sm" kind="primary" icon="plus">New session</Btn>
        </div>
      </div>
      {sessions.length === 0 ? (
        <div className="empty">
          <div className="ico-wrap"><Icon name="zap" size={18} /></div>
          <div className="head">No sessions</div>
          <div className="sub">Start a session to run an agent (or graph) against this workspace.</div>
        </div>
      ) : (
        <div className="tbl-wrap">
          <table className="tbl">
            <thead><tr><th>Status</th><th>Session</th><th>Agent</th><th>Turns</th><th>Last turn</th></tr></thead>
            <tbody>
              {sessions.map((s) => (
                <tr key={s.id} onClick={() => onOpen(s.id)}>
                  <td><StatusPill status={s.status} /></td>
                  <td className="mono">{s.id}</td>
                  <td className="mono">{s.agent_id || s.graph_id}</td>
                  <td className="mono num tabular">{s.turn_count}</td>
                  <td className="mono muted">{s.last_turn_at ? relativeTime((Date.now() - s.last_turn_at.getTime()) / 1000) : "—"}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}

// ----- Log tab ------

function LogTab() {
  const [limit, setLimit] = React.useState(50);
  const entries = window.MOCK.GIT_LOG.slice(0, limit);
  return (
    <div style={{ padding: 14 }}>
      <div className="muted text-sm mb-3">
        <span className="mono">git log</span> of the workspace's <span className="mono">.state</span> repository · default limit 50, max 500
      </div>
      <div style={{ position: "relative", paddingLeft: 18 }}>
        <div style={{ position: "absolute", left: 6, top: 6, bottom: 6, width: 1, background: "var(--border)" }}></div>
        {entries.map((e, i) => (
          <div key={e.sha} style={{ position: "relative", padding: "6px 0 6px 16px", display: "flex", alignItems: "center", gap: 10 }}>
            <div style={{ position: "absolute", left: -4, top: 9, width: 11, height: 11, borderRadius: "50%", background: "var(--bg-2)", border: "2px solid var(--accent)" }}></div>
            <span className="mono" style={{ color: "var(--accent)", fontSize: 12, fontWeight: 500 }}>{e.sha}</span>
            <span className="muted mono text-sm">{relativeTime(e.at)}</span>
            <span style={{ fontSize: 12.5 }}>"{e.msg}"</span>
          </div>
        ))}
      </div>
      <div style={{ marginTop: 14, display: "flex", justifyContent: "center" }}>
        {limit < 500 && (
          <Btn size="sm" kind="ghost" onClick={() => setLimit(Math.min(500, limit + 50))}>Load more</Btn>
        )}
      </div>
    </div>
  );
}

// ----- Config tab ------

function ConfigTab({ workspaceId, detail }) {
  return (
    <div style={{ padding: 14 }}>
      <div className="muted text-sm mb-3">
        Materialised template + overrides. Lines in <strong>bold</strong> were injected by overrides.
      </div>
      <div className="code-block" style={{ maxHeight: 460, overflow: "auto" }}>
        <span className="com"># template: {detail.template}</span>{"\n"}
        <span className="com"># provider: {detail.provider}</span>{"\n"}
        <span className="com"># workspace_id: {workspaceId}</span>{"\n\n"}
        <span className="key">image</span>: <span className="str">"python:3.11-slim"</span>{"\n"}
        <span className="key">workdir</span>: <span className="str">"/workspace"</span>{"\n\n"}
        <span className="key">env</span>:{"\n"}
        {"  "}<span className="key">PYTHONUNBUFFERED</span>: <span className="str">"1"</span>{"\n"}
        {"  "}<span className="key">MATRIX_SESSION_ID</span>: <span className="str">"&lt;injected&gt;"</span>{"\n"}
        {"  "}<span style={{ fontWeight: 700, color: "var(--text)" }}>STRIPE_API_KEY: <span className="str">"sk_test_..." </span></span>
        <span style={{ background: "var(--accent-dim)", color: "var(--accent)", padding: "0 4px", borderRadius: 3, fontSize: 10, marginLeft: 4 }}>override</span>{"\n\n"}
        <span className="key">init_commands</span>:{"\n"}
        {"  "}- <span className="str">"pip install -r requirements.txt"</span>{"\n"}
        {"  "}- <span style={{ fontWeight: 700, color: "var(--text)" }}>"apt install -y jq" </span>
        <span style={{ background: "var(--accent-dim)", color: "var(--accent)", padding: "0 4px", borderRadius: 3, fontSize: 10, marginLeft: 4 }}>override</span>{"\n\n"}
        <span className="key">resources</span>:{"\n"}
        {"  "}<span className="key">cpu</span>: <span className="num">2</span>{"\n"}
        {"  "}<span className="key">memory</span>: <span className="str">"4Gi"</span>{"\n"}
      </div>
    </div>
  );
}

// ----- Destroy tab ------

function DestroyTab({ workspaceId, wsSessions, onOpen }) {
  const active = wsSessions.filter((s) => !["ended", "failed", "cancelled"].includes(s.status));
  return (
    <div style={{ padding: 14 }}>
      <Banner
        kind="error"
        title="Permanent action"
        detail="Destroying a workspace cancels any in-flight sessions, deletes the .state repo, and removes all files. This cannot be undone."
      />
      <div className="kv mt-3" style={{ gridTemplateColumns: "160px 1fr" }}>
        <dt>workspace</dt><dd>{workspaceId}</dd>
        <dt>active sessions</dt><dd>{active.length} {active.length > 0 && <span className="muted">(will be cancelled)</span>}</dd>
        <dt>total sessions</dt><dd>{wsSessions.length}</dd>
      </div>
      <div className="mt-4">
        <Btn kind="danger" icon="trash" onClick={onOpen}>Destroy workspace</Btn>
      </div>
    </div>
  );
}

window.WorkspacesPage = WorkspacesPage;
window.WorkspaceDetail = WorkspaceDetail;

function ChannelsTab({ workspaceId, pushToast, onNavigate }) {
  const associations = (window.CHANNEL_ASSOCIATIONS || []).filter((a) => a.workspace_id === workspaceId);
  const channelsData = window.CHANNELS_DATA || [];
  const [showLink, setShowLink] = React.useState(false);
  const [rows, setRows] = React.useState(associations);

  const toggle = (id, field) => {
    setRows((arr) => arr.map((r) => r.id === id ? { ...r, [field]: !r[field] } : r));
    pushToast({ kind: "info", title: "Association updated", detail: `PUT /v1/workspace_channel_associations/${id}` });
  };
  const remove = (id) => {
    setRows((arr) => arr.filter((r) => r.id !== id));
    pushToast({ kind: "warning", title: "Association removed", detail: `DELETE /v1/workspace_channel_associations/${id}` });
  };

  return (
    <div style={{ padding: 14 }}>
      <div style={{ display: "flex", alignItems: "center", marginBottom: 10 }}>
        <div>
          <div className="text-sm muted">Channels associated with this workspace</div>
        </div>
        <div style={{ marginLeft: "auto" }}>
          <Btn size="sm" kind="primary" icon="plus" onClick={() => setShowLink(true)}>Link channel</Btn>
        </div>
      </div>
      {rows.length === 0 ? (
        <div className="empty">
          <div className="ico-wrap"><Icon name="bell" size={18} /></div>
          <div className="head">No channels linked</div>
          <div className="sub">Link an external channel (Slack, Telegram, Discord) to fan out yielding-tool events from this workspace.</div>
          <div className="actions">
            <Btn size="sm" kind="primary" icon="plus" onClick={() => setShowLink(true)}>Link channel</Btn>
          </div>
        </div>
      ) : (
        <div className="tbl-wrap">
          <table className="tbl">
            <thead>
              <tr>
                <th>Channel</th>
                <th>External</th>
                <th>Enabled</th>
                <th>ask_user</th>
                <th>tool_approval</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              {rows.map((a) => {
                const ch = channelsData.find((c) => c.id === a.channel_id);
                return (
                  <tr key={a.id} style={{ opacity: a.enabled ? 1 : 0.55 }}>
                    <td className="mono">{a.channel_id} {ch && <span className="muted text-sm">· {ch.label}</span>}</td>
                    <td className="mono muted text-sm">{ch?.external_id || "—"}</td>
                    <td><Toggle on={a.enabled} onChange={() => toggle(a.id, "enabled")} /></td>
                    <td><Toggle on={a.forward_ask_user} onChange={() => toggle(a.id, "forward_ask_user")} /></td>
                    <td><Toggle on={a.forward_tool_approval} onChange={() => toggle(a.id, "forward_tool_approval")} /></td>
                    <td style={{ textAlign: "right", paddingRight: 12 }}>
                      <button className="icon-btn" style={{ width: 22, height: 22 }} title="Remove" onClick={() => remove(a.id)}><Icon name="x" size={10} /></button>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}
      {showLink && (
        <Modal
          title="Link channel"
          onClose={() => setShowLink(false)}
          footer={<><Btn kind="ghost" onClick={() => setShowLink(false)}>Cancel</Btn><Btn kind="primary" icon="plus" onClick={() => { setShowLink(false); pushToast({ kind: "success", title: "Channel linked", detail: `POST /v1/workspaces/${workspaceId}/channel_associations → 201` }); }}>Link</Btn></>}
        >
          <div className="field" style={{ marginBottom: 12 }}>
            <label className="field-label">workspace <span className="hint">auto-filled</span></label>
            <input className="input mono" value={workspaceId} readOnly style={{ width: "100%" }} />
          </div>
          <div className="field">
            <label className="field-label">channel</label>
            <select className="select mono" style={{ width: "100%" }}>
              {channelsData.map((c) => <option key={c.id}>{c.id} · {c.label}</option>)}
            </select>
          </div>
          <div className="field" style={{ display: "flex", flexDirection: "column", gap: 6 }}>
            <label style={{ display: "inline-flex", alignItems: "center", gap: 8, fontSize: 12.5 }}>
              <input type="checkbox" defaultChecked /><span>Enabled</span>
            </label>
            <label style={{ display: "inline-flex", alignItems: "center", gap: 8, fontSize: 12.5 }}>
              <input type="checkbox" defaultChecked /><span>Forward ask_user prompts</span>
            </label>
            <label style={{ display: "inline-flex", alignItems: "center", gap: 8, fontSize: 12.5 }}>
              <input type="checkbox" defaultChecked /><span>Forward tool_approval requests</span>
            </label>
          </div>
        </Modal>
      )}
    </div>
  );
}

function Toggle({ on, onChange }) {
  return (
    <button
      onClick={onChange}
      style={{
        width: 32, height: 18, borderRadius: 10,
        background: on ? "var(--accent)" : "var(--bg-2)",
        border: `1px solid ${on ? "var(--accent)" : "var(--border)"}`,
        cursor: "pointer", padding: 0, position: "relative", transition: "0.15s",
      }}
    >
      <span style={{
        position: "absolute", top: 1, left: on ? 15 : 1,
        width: 14, height: 14, borderRadius: "50%",
        background: on ? "var(--accent-fg)" : "var(--text-3)",
        transition: "0.15s",
      }} />
    </button>
  );
}
