"""DB-backed artifact storage — the default ``ArtifactStorage`` implementation.

Persists each artifact as an :class:`primer.model.artifact.Artifact` row through
the platform StorageProvider. Bytes live in their own table (base64 in JSON
storage), keeping media out of the ``ChatMessage`` row while staying swappable
for a filesystem/S3 backend later.
"""

from __future__ import annotations

from primer.int.artifact_storage import ArtifactBlob, ArtifactStorage
from primer.int.storage_provider import StorageProvider
from primer.model.artifact import Artifact


class DbArtifactStorage(ArtifactStorage):
    """Stores artifacts as ``Artifact`` rows in the platform storage."""

    def __init__(self, storage_provider: StorageProvider) -> None:
        self._sp = storage_provider

    async def initialize(self) -> None:
        return None

    async def put(
        self, *, data: bytes, mime_type: str, filename: str | None = None,
    ) -> str:
        artifact = Artifact(
            mime_type=mime_type, filename=filename, size=len(data), data=data,
        )
        created = await self._sp.get_storage(Artifact).create(artifact)
        # id is autogenerated by Identifiable at construction; create() returns
        # the persisted row with the same id.
        return created.id or artifact.id  # type: ignore[return-value]

    async def get(self, artifact_id: str) -> ArtifactBlob | None:
        row = await self._sp.get_storage(Artifact).get(artifact_id)
        if row is None:
            return None
        return ArtifactBlob(
            data=row.data, mime_type=row.mime_type, filename=row.filename,
        )

    async def delete(self, artifact_id: str) -> None:
        await self._sp.get_storage(Artifact).delete(artifact_id)

    async def aclose(self) -> None:
        return None


__all__ = ["DbArtifactStorage"]
