"""E2E: CrossEncoderProvider explicit CRUD round-trip.

Covers backlog item T0154. Earlier batches only smoke-tested the CRUD
generator on LLMProvider and Toolset — this is the explicit positive
control for the CrossEncoderProvider router (also generated by the
same factory, so a regression in the factory would fan out to all
three families; this test is a tripwire for the family the suite has
otherwise barely touched).

NB: CrossEncoderProvider extends Identifiable (no description field),
so the PUT step mutates `limits.max_concurrency` to verify the row
update is observable through GET.
"""

from __future__ import annotations

import httpx
import pytest


def _ce_provider_body(entity_id: str) -> dict:
    return {
        "id": entity_id,
        "provider": "huggingface",
        "models": [{"name": "BAAI/bge-reranker-v2-m3"}],
        "config": {"token": None},
        "limits": {"max_concurrency": 2},
    }


@pytest.mark.asyncio
async def test_t0154_cross_encoder_provider_crud_with_invalidate(
    client: httpx.AsyncClient, unique_suffix: str,
) -> None:
    """T0154 — full CRUD cycle for CrossEncoderProvider:
    create → get → put (mutate) → get (reflects) → invalidate (204)
    → delete (204) → get (404).
    """
    entity_id = f"ce-{unique_suffix}"
    base = "/v1/cross_encoder_providers"
    body = _ce_provider_body(entity_id)

    create = await client.post(base, json=body)
    assert create.status_code == 201, create.text
    assert create.json()["id"] == entity_id

    got = await client.get(f"{base}/{entity_id}")
    assert got.status_code == 200, got.text
    assert got.json()["id"] == entity_id

    # PUT mutating limits.max_concurrency (no description field on
    # this entity, so this is the available observable mutation)
    updated = _ce_provider_body(entity_id)
    updated["limits"] = {"max_concurrency": 16}
    put = await client.put(f"{base}/{entity_id}", json=updated)
    assert put.status_code == 200, put.text
    assert put.json()["limits"]["max_concurrency"] == 16

    got2 = await client.get(f"{base}/{entity_id}")
    assert got2.json()["limits"]["max_concurrency"] == 16

    inv = await client.post(f"{base}/{entity_id}/invalidate")
    assert inv.status_code == 204, inv.text

    rm = await client.delete(f"{base}/{entity_id}")
    assert rm.status_code == 204, rm.text

    gone = await client.get(f"{base}/{entity_id}")
    assert gone.status_code == 404, gone.text
    assert gone.json()["type"] == "/errors/not-found"


# ============================================================================
# T0234 — CrossEncoderProvider /models echoes configured names
# ============================================================================


@pytest.mark.asyncio
async def test_t0234_cross_encoder_models_endpoint_is_row_cached(
    client: httpx.AsyncClient, unique_suffix: str,
) -> None:
    """T0234 — Mirror of T0025 (LLM) and T0175 (Embedder) for the
    CrossEncoder family: GET /v1/cross_encoder_providers/{id}/models
    must echo the configured model names without touching the network.
    """
    entity_id = f"ce-row-{unique_suffix}"
    body = {
        "id": entity_id,
        "provider": "huggingface",
        "models": [
            {"name": "BAAI/bge-reranker-v2-m3"},
            {"name": "cross-encoder/ms-marco-MiniLM-L-6-v2"},
        ],
        "config": {"token": None},
        "limits": {"max_concurrency": 1},
    }
    create = await client.post("/v1/cross_encoder_providers", json=body)
    assert create.status_code == 201, create.text

    try:
        resp = await client.get(
            f"/v1/cross_encoder_providers/{entity_id}/models",
            timeout=httpx.Timeout(15.0, connect=5.0),
        )
        assert resp.status_code == 200, resp.text
        body_out = resp.json()
        assert "models" in body_out, body_out
        assert sorted(body_out["models"]) == sorted([
            "BAAI/bge-reranker-v2-m3",
            "cross-encoder/ms-marco-MiniLM-L-6-v2",
        ]), body_out
    finally:
        await client.delete(f"/v1/cross_encoder_providers/{entity_id}")


# ============================================================================
# T0235 — CrossEncoderProvider /invalidate asymmetry with /models
# ============================================================================


@pytest.mark.asyncio
async def test_t0235_cross_encoder_invalidate_and_models_asymmetry(
    client: httpx.AsyncClient, unique_suffix: str,
) -> None:
    """T0235 — Mirror of T0187 + T0188 for the CrossEncoder family:
    /invalidate on a missing row is silent 204 (unconditional cache
    drop), while /models on the same missing id is 404. Pins the
    asymmetric contract is consistent across all three provider families.
    """
    missing_id = f"missing-ce-{unique_suffix}"

    inv = await client.post(
        f"/v1/cross_encoder_providers/{missing_id}/invalidate",
    )
    assert inv.status_code == 204, (
        f"invalidate on missing CE row should be 204; got "
        f"{inv.status_code}: {inv.text}"
    )
    assert inv.content == b"", inv.content

    models = await client.get(
        f"/v1/cross_encoder_providers/{missing_id}/models",
    )
    assert models.status_code == 404, models.text
    envelope = models.json()
    assert envelope["type"] == "/errors/not-found", envelope
