"""Entities for the channels feature."""

from __future__ import annotations

from enum import Enum
from typing import Annotated, Union

from pydantic import BaseModel, Field, SecretStr, field_validator, model_validator

from matrix.model.common import Identifiable


class ChannelProviderType(str, Enum):
    SLACK = "slack"
    TELEGRAM = "telegram"
    DISCORD = "discord"


class SlackChannelProviderConfig(BaseModel):
    """Credentials for one Slack workspace (Slack-team)."""

    app_token: SecretStr = Field(
        ...,
        description=(
            "App-level token (xapp-…) required for Socket Mode. "
            "Generated in the Slack app's Basic Information panel."
        ),
    )
    bot_token: SecretStr = Field(
        ...,
        description=(
            "Bot OAuth token (xoxb-…) used for chat.postMessage, "
            "conversations.history, etc."
        ),
    )
    signing_secret: SecretStr | None = Field(
        default=None,
        description=(
            "Optional. Unused in Socket Mode (signing only matters "
            "for HTTP event delivery)."
        ),
    )

    # Per-field validators so loc tuples carry the field name
    # (loc=("body","config","app_token") etc.), letting the UI modal
    # render an inline error under the offending field. A combined
    # @model_validator would flatten the loc to ("body",) and the
    # modal's per-field error lookup would miss it entirely.
    @field_validator("app_token")
    @classmethod
    def _validate_app_token(cls, v: SecretStr) -> SecretStr:
        if not v.get_secret_value().startswith("xapp-"):
            raise ValueError(
                "app_token must start with 'xapp-' (Slack app-level token)"
            )
        return v

    @field_validator("bot_token")
    @classmethod
    def _validate_bot_token(cls, v: SecretStr) -> SecretStr:
        if not v.get_secret_value().startswith("xoxb-"):
            raise ValueError(
                "bot_token must start with 'xoxb-' (Slack bot token)"
            )
        return v


class TelegramChannelProviderConfig(BaseModel):
    """One Telegram bot token + polling knob."""

    bot_token: SecretStr = Field(
        ...,
        description=(
            "Telegram bot token in '123456:ABCDEF…' shape "
            "(generated by @BotFather)."
        ),
    )
    poll_timeout_seconds: int = Field(
        default=25, ge=1, le=60,
        description=(
            "Long-poll timeout per getUpdates call. Telegram caps "
            "at 50; 25 balances latency vs connection churn."
        ),
    )

    @field_validator("bot_token")
    @classmethod
    def _validate_bot_token(cls, v: SecretStr) -> SecretStr:
        tok = v.get_secret_value()
        if ":" not in tok or len(tok) < 20:
            raise ValueError(
                "bot_token must be in the '123456:ABCDEF...' shape"
            )
        return v


class DiscordChannelProviderConfig(BaseModel):
    """One Discord bot token + intent toggle."""

    bot_token: SecretStr = Field(
        ...,
        description=(
            "Discord bot token from the Developer Portal. Do NOT "
            "include the 'Bot ' prefix; the adapter adds it."
        ),
    )
    enable_dms: bool = Field(
        default=True,
        description=(
            "Request dm_messages intent so the bot can read DM "
            "channels. Turn off for guild-only deployments."
        ),
    )

    @field_validator("bot_token")
    @classmethod
    def _validate_bot_token(cls, v: SecretStr) -> SecretStr:
        tok = v.get_secret_value()
        if not tok or len(tok) < 30:
            raise ValueError(
                "bot_token must be the Developer Portal bot token "
                "(>=30 chars); do NOT include the 'Bot ' prefix"
            )
        return v


ChannelProviderConfig = Annotated[
    Union[
        SlackChannelProviderConfig,
        TelegramChannelProviderConfig,
        DiscordChannelProviderConfig,
    ],
    Field(description="Platform-specific config; must match parent provider."),
]


class ChannelProvider(Identifiable):
    """A configured messaging-platform credential set."""

    provider: ChannelProviderType = Field(...)
    config: ChannelProviderConfig = Field(...)

    @model_validator(mode="before")
    @classmethod
    def _coerce_config_type(cls, values):
        """When ``config`` is a plain dict, construct the right config type.

        Pydantic union parsing always picks the first matching variant
        (``SlackChannelProviderConfig`` for ``{}``) regardless of the
        ``provider`` value. We intercept *before* field parsing so we
        can inject the correct concrete type from the provider name.
        """
        if not isinstance(values, dict):
            return values
        provider_val = values.get("provider")
        config_val = values.get("config")
        if provider_val is None or not isinstance(config_val, dict):
            return values
        # Resolve the provider string (may be an enum value or string).
        pv = provider_val.value if hasattr(provider_val, "value") else str(provider_val)
        cls_map = {
            "slack": SlackChannelProviderConfig,
            "telegram": TelegramChannelProviderConfig,
            "discord": DiscordChannelProviderConfig,
        }
        config_cls = cls_map.get(pv)
        if config_cls is not None:
            values = dict(values)
            values["config"] = config_cls(**config_val)
        return values

    @model_validator(mode="after")
    def _validate_config_matches(self) -> "ChannelProvider":
        match self.provider:
            case ChannelProviderType.SLACK:
                if not isinstance(self.config, SlackChannelProviderConfig):
                    raise ValueError(
                        "provider='slack' requires a SlackChannelProviderConfig"
                    )
            case ChannelProviderType.TELEGRAM:
                if not isinstance(self.config, TelegramChannelProviderConfig):
                    raise ValueError(
                        "provider='telegram' requires a TelegramChannelProviderConfig"
                    )
            case ChannelProviderType.DISCORD:
                if not isinstance(self.config, DiscordChannelProviderConfig):
                    raise ValueError(
                        "provider='discord' requires a DiscordChannelProviderConfig"
                    )
        return self


class Channel(Identifiable):
    """One conversational target within a ChannelProvider."""

    provider_id: str = Field(..., min_length=1)
    external_id: str = Field(..., min_length=1)
    label: str = Field(default="", max_length=200)


class WorkspaceChannelAssociation(Identifiable):
    """Many-to-many link between a workspace and a channel."""

    workspace_id: str = Field(..., min_length=1)
    channel_id: str = Field(..., min_length=1)
    enabled: bool = Field(default=True)
    forward_ask_user: bool = Field(default=True)
    forward_tool_approval: bool = Field(default=True)


__all__ = [
    "Channel",
    "ChannelProvider",
    "ChannelProviderConfig",
    "ChannelProviderType",
    "DiscordChannelProviderConfig",
    "SlackChannelProviderConfig",
    "TelegramChannelProviderConfig",
    "WorkspaceChannelAssociation",
]
