"""RFC 7807 problem+json error model and FastAPI handler registration.

Single ``ProblemDetails`` Pydantic model + an exception-handler chain
that maps every :class:`matrix.model.except_.MatrixError` subclass to
the right HTTP status + problem-type URI. Type URIs are relative
(``/errors/<code>``) per RFC 7807 §3.1.
"""

from __future__ import annotations

import logging
from typing import Any

from fastapi import FastAPI, Request
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field

from matrix.model.except_ import (
    AuthenticationError,
    AuthRequiredError,
    BadRequestError,
    ConfigError,
    ConflictError,
    MatrixError,
    ModelNotFoundError,
    NetworkError,
    NotFoundError,
    ProviderError,
    RateLimitError,
    ServerError,
    UnsupportedContentError,
)


logger = logging.getLogger(__name__)


PROBLEM_JSON_MEDIA_TYPE = "application/problem+json"


class ProblemDetails(BaseModel):
    """RFC 7807 problem details object."""

    type: str = Field(
        ...,
        description="URI reference identifying the problem type.",
    )
    title: str = Field(
        ...,
        description="Short, human-readable summary of the problem type.",
    )
    status: int = Field(
        ...,
        description="HTTP status code generated by the origin server.",
    )
    detail: str = Field(
        ...,
        description="Human-readable explanation specific to this occurrence.",
    )
    instance: str | None = Field(
        default=None,
        description="URI reference identifying the specific occurrence (request path).",
    )
    extensions: dict[str, Any] | None = Field(
        default=None,
        description="Extension members per RFC 7807 §3.2.",
    )


# Order matters: handlers are checked most-specific first. We list the
# more-derived classes BEFORE their bases so a MatrixError-base lookup
# falls through to the most specific match.
_MATRIX_ERROR_MAP: list[tuple[type[MatrixError], int, str, str]] = [
    (BadRequestError, 400, "/errors/bad-request", "Bad Request"),
    (AuthenticationError, 401, "/errors/authentication-failed", "Authentication Failed"),
    (AuthRequiredError, 401, "/errors/auth-required", "Authentication Required"),
    (ModelNotFoundError, 404, "/errors/model-not-found", "Model Not Found"),
    (NotFoundError, 404, "/errors/not-found", "Not Found"),
    (ConflictError, 409, "/errors/conflict", "Conflict"),
    (RateLimitError, 429, "/errors/rate-limited", "Rate Limited"),
    (UnsupportedContentError, 422, "/errors/unsupported-content", "Unsupported Content"),
    (ServerError, 502, "/errors/provider-server-error", "Provider Server Error"),
    (ProviderError, 502, "/errors/provider-error", "Provider Error"),
    (NetworkError, 504, "/errors/network-error", "Network Error"),
    (ConfigError, 500, "/errors/misconfigured", "Misconfigured"),
    (MatrixError, 500, "/errors/internal", "Internal Error"),
]


_RESPONSES_BY_CODE: dict[int, dict[str, Any]] = {}
for _exc, _status, _uri, _title in _MATRIX_ERROR_MAP:
    _RESPONSES_BY_CODE.setdefault(
        _status,
        {
            "model": ProblemDetails,
            "description": _title,
            "content": {PROBLEM_JSON_MEDIA_TYPE: {}},
        },
    )
_RESPONSES_BY_CODE.setdefault(
    422,
    {
        "model": ProblemDetails,
        "description": "Validation Error",
        "content": {PROBLEM_JSON_MEDIA_TYPE: {}},
    },
)


def common_responses(*codes: int) -> dict[int, dict[str, Any]]:
    """Return a FastAPI ``responses=`` map for the given status codes.

    Use on every route that can return one of the documented error codes
    so OpenAPI shows the ProblemDetails schema for each.

    Raises
    ------
    KeyError
        ``codes`` references a status code not in the error map.
    """
    return {code: _RESPONSES_BY_CODE[code] for code in codes}


def _problem_response(
    *,
    request: Request,
    status: int,
    type_uri: str,
    title: str,
    detail: str,
    extensions: dict[str, Any] | None = None,
) -> JSONResponse:
    problem = ProblemDetails(
        type=type_uri,
        title=title,
        status=status,
        detail=detail,
        instance=request.url.path,
        extensions=extensions,
    )
    return JSONResponse(
        status_code=status,
        content=problem.model_dump(exclude_none=True),
        media_type=PROBLEM_JSON_MEDIA_TYPE,
    )


def _make_matrix_error_handler(status: int, type_uri: str, title: str):
    async def _handler(request: Request, exc: MatrixError) -> JSONResponse:
        extensions: dict[str, Any] | None = None
        if isinstance(exc, AuthRequiredError):
            extensions = {"auth_url": exc.auth_url}
        return _problem_response(
            request=request,
            status=status,
            type_uri=type_uri,
            title=title,
            detail=exc.message,
            extensions=extensions,
        )

    return _handler


async def _validation_error_handler(
    request: Request, exc: RequestValidationError
) -> JSONResponse:
    return _problem_response(
        request=request,
        status=422,
        type_uri="/errors/validation-error",
        title="Validation Error",
        detail="One or more request parameters or body fields failed validation.",
        extensions={"errors": exc.errors()},
    )


async def _bare_exception_handler(
    request: Request, exc: Exception
) -> JSONResponse:
    logger.exception(
        "unhandled exception in API request",
        extra={"path": request.url.path, "exception_type": type(exc).__name__},
    )
    return _problem_response(
        request=request,
        status=500,
        type_uri="/errors/internal",
        title="Internal Error",
        detail="An unexpected error occurred. The incident has been logged.",
    )


def register_error_handlers(app: FastAPI) -> None:
    """Install one exception handler per row in the error map.

    The bare-exception handler is registered against HTTP status code
    500 (not the ``Exception`` class) because Starlette's
    ``ServerErrorMiddleware`` lives outside ``ExceptionMiddleware`` and
    only consults the status-code registry, not the class registry,
    for unhandled exceptions.
    """
    for exc_cls, status, type_uri, title in _MATRIX_ERROR_MAP:
        app.add_exception_handler(
            exc_cls, _make_matrix_error_handler(status, type_uri, title)
        )
    app.add_exception_handler(RequestValidationError, _validation_error_handler)
    # Status-code 500 override; this is what catches unhandled non-MatrixError
    # exceptions inside ServerErrorMiddleware.
    app.add_exception_handler(500, _bare_exception_handler)


__all__ = [
    "PROBLEM_JSON_MEDIA_TYPE",
    "ProblemDetails",
    "common_responses",
    "register_error_handlers",
]
