"""Update paths reuse the path id when the body omits it.

With ``Identifiable.id`` now optional + autogenerated on create, an
update whose body omits the id must NOT autogenerate a fresh random id
and then fail the body-vs-path mismatch check. It must adopt the path
id. A body that supplies a DIFFERENT explicit id still conflicts.

These cover the internal ``_system`` toolset update handler; the REST
PUT handler shares the same injection logic.
"""

from __future__ import annotations

import json
from typing import Any

import pytest
from pydantic import SecretStr

from primer.api.registries import ProviderRegistry
from primer.model.agent import Agent, AgentModel
from primer.model.except_ import ConflictError, NotFoundError
from primer.model.storage import CursorPageResponse, OffsetPageResponse
from primer.toolset.system import build_system_toolset


class _Storage:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}

    async def get(self, id: str) -> Any | None:
        return self._data.get(id)

    async def create(self, e: Any) -> Any:
        if e.id in self._data:
            raise ConflictError(f"id {e.id!r} already exists")
        self._data[e.id] = e
        return e

    async def update(self, e: Any) -> Any:
        if e.id not in self._data:
            raise NotFoundError(f"no entity with id {e.id!r}")
        self._data[e.id] = e
        return e

    async def delete(self, id: str) -> None:
        if id not in self._data:
            raise NotFoundError(f"no entity with id {id!r}")
        del self._data[id]

    async def list(self, page, *, order_by=None):
        items = list(self._data.values())
        from primer.model.storage import OffsetPage

        if isinstance(page, OffsetPage):
            sliced = items[page.offset : page.offset + page.length]
            return OffsetPageResponse(
                offset=page.offset,
                length=len(sliced),
                total=len(items),
                items=sliced,
            )
        offset = int(page.cursor) if page.cursor else 0
        sliced = items[offset : offset + page.length]
        next_cursor = (
            str(offset + page.length)
            if offset + page.length < len(items)
            else None
        )
        return CursorPageResponse(next_cursor=next_cursor, items=sliced)

    async def find(self, predicate, page, *, order_by=None):
        return await self.list(page, order_by=order_by)


class _SP:
    def __init__(self) -> None:
        self._stores: dict[type, _Storage] = {}

    def get_storage(self, cls: type) -> _Storage:
        return self._stores.setdefault(cls, _Storage())

    async def initialize(self) -> None:
        return

    async def aclose(self) -> None:
        return


@pytest.fixture
def sp() -> _SP:
    return _SP()


@pytest.fixture
def pr(sp: _SP) -> ProviderRegistry:
    return ProviderRegistry(
        sp,  # type: ignore[arg-type]
        llm_factory=lambda p: object(),
        embedder_factory=lambda p: object(),
        cross_encoder_factory=lambda p: object(),
        toolset_factory=lambda t: object(),
    )


@pytest.fixture
def system_toolset(sp: _SP, pr: ProviderRegistry):
    provider = build_system_toolset(
        storage_provider=sp,  # type: ignore[arg-type]
        provider_registry=pr,
    )
    pr._system_toolset_provider = provider  # type: ignore[attr-defined]
    return provider


def _agent(agent_id: str, description: str) -> Agent:
    return Agent(
        id=agent_id,
        description=description,
        model=AgentModel(
            provider_id="anthropic-1", model_name="claude-sonnet-4-6"
        ),
        temperature=0.0,
        tools=[],
        system_prompt=["you are a test"],
    )


@pytest.mark.asyncio
async def test_update_with_omitted_id_uses_path_id(system_toolset) -> None:
    seed = _agent("a1", "before").model_dump(mode="json")
    result = await system_toolset.call(
        tool_name="create_agent", arguments={"entity": seed}
    )
    assert not result.is_error, result.output

    body = _agent("a1", "after").model_dump(mode="json")
    body.pop("id")
    result = await system_toolset.call(
        tool_name="update_agent", arguments={"id": "a1", "entity": body}
    )
    assert not result.is_error, result.output
    updated = json.loads(result.output)
    assert updated["id"] == "a1"
    assert updated["description"] == "after"

    result = await system_toolset.call(
        tool_name="get_agent", arguments={"id": "a1"}
    )
    assert not result.is_error
    assert json.loads(result.output)["description"] == "after"


@pytest.mark.asyncio
async def test_update_with_mismatched_id_still_conflicts(system_toolset) -> None:
    seed = _agent("a2", "before").model_dump(mode="json")
    result = await system_toolset.call(
        tool_name="create_agent", arguments={"entity": seed}
    )
    assert not result.is_error, result.output

    body = _agent("different", "after").model_dump(mode="json")
    result = await system_toolset.call(
        tool_name="update_agent", arguments={"id": "a2", "entity": body}
    )
    assert result.is_error
    assert json.loads(result.output)["type"] == "conflict"
