"""Update paths reuse the path id when the body omits it.

With ``Identifiable.id`` now optional + autogenerated on create, an
update whose body omits the id must NOT autogenerate a fresh random id
and then fail the body-vs-path mismatch check. It must adopt the path
id. A body that supplies a DIFFERENT explicit id still conflicts.

These cover the internal ``_system`` toolset update handler; the REST
PUT handler shares the same injection logic.
"""

from __future__ import annotations

import json
import re
from collections.abc import AsyncIterator
from typing import Any, ClassVar

import httpx
import pytest
import pytest_asyncio
from httpx import ASGITransport
from fastapi import FastAPI

from primer.api.errors import register_error_handlers
from primer.api.registries import ProviderRegistry
from primer.api.routers._crud import make_crud_router
from primer.model.agent import Agent, AgentModel
from primer.model.common import Identifiable
from primer.model.except_ import ConflictError, NotFoundError
from primer.model.storage import CursorPageResponse, OffsetPageResponse
from primer.toolset.system import build_system_toolset


class _Storage:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}

    async def get(self, id: str) -> Any | None:
        return self._data.get(id)

    async def create(self, e: Any) -> Any:
        if e.id in self._data:
            raise ConflictError(f"id {e.id!r} already exists")
        self._data[e.id] = e
        return e

    async def update(self, e: Any) -> Any:
        if e.id not in self._data:
            raise NotFoundError(f"no entity with id {e.id!r}")
        self._data[e.id] = e
        return e

    async def delete(self, id: str) -> None:
        if id not in self._data:
            raise NotFoundError(f"no entity with id {id!r}")
        del self._data[id]

    async def list(self, page, *, order_by=None):
        items = list(self._data.values())
        from primer.model.storage import OffsetPage

        if isinstance(page, OffsetPage):
            sliced = items[page.offset : page.offset + page.length]
            return OffsetPageResponse(
                offset=page.offset,
                length=len(sliced),
                total=len(items),
                items=sliced,
            )
        offset = int(page.cursor) if page.cursor else 0
        sliced = items[offset : offset + page.length]
        next_cursor = (
            str(offset + page.length)
            if offset + page.length < len(items)
            else None
        )
        return CursorPageResponse(next_cursor=next_cursor, items=sliced)

    async def find(self, predicate, page, *, order_by=None):
        return await self.list(page, order_by=order_by)


class _SP:
    def __init__(self) -> None:
        self._stores: dict[type, _Storage] = {}

    def get_storage(self, cls: type) -> _Storage:
        return self._stores.setdefault(cls, _Storage())

    async def initialize(self) -> None:
        return

    async def aclose(self) -> None:
        return


@pytest.fixture
def sp() -> _SP:
    return _SP()


@pytest.fixture
def pr(sp: _SP) -> ProviderRegistry:
    return ProviderRegistry(
        sp,  # type: ignore[arg-type]
        llm_factory=lambda p: object(),
        embedder_factory=lambda p: object(),
        cross_encoder_factory=lambda p: object(),
        toolset_factory=lambda t: object(),
    )


@pytest.fixture
def system_toolset(sp: _SP, pr: ProviderRegistry):
    provider = build_system_toolset(
        storage_provider=sp,  # type: ignore[arg-type]
        provider_registry=pr,
    )
    pr._system_toolset_provider = provider  # type: ignore[attr-defined]
    return provider


def _agent(agent_id: str, description: str) -> Agent:
    return Agent(
        id=agent_id,
        description=description,
        model=AgentModel(
            provider_id="anthropic-1", model_name="claude-sonnet-4-6"
        ),
        temperature=0.0,
        tools=[],
        system_prompt=["you are a test"],
    )


@pytest.mark.asyncio
async def test_update_with_omitted_id_uses_path_id(system_toolset) -> None:
    seed = _agent("a1", "before").model_dump(mode="json")
    result = await system_toolset.call(
        tool_name="create_agent", arguments={"entity": seed}
    )
    assert not result.is_error, result.output

    body = _agent("a1", "after").model_dump(mode="json")
    body.pop("id")
    result = await system_toolset.call(
        tool_name="update_agent", arguments={"id": "a1", "entity": body}
    )
    assert not result.is_error, result.output
    updated = json.loads(result.output)
    assert updated["id"] == "a1"
    assert updated["description"] == "after"

    result = await system_toolset.call(
        tool_name="get_agent", arguments={"id": "a1"}
    )
    assert not result.is_error
    assert json.loads(result.output)["description"] == "after"


@pytest.mark.asyncio
async def test_update_with_mismatched_id_still_conflicts(system_toolset) -> None:
    seed = _agent("a2", "before").model_dump(mode="json")
    result = await system_toolset.call(
        tool_name="create_agent", arguments={"entity": seed}
    )
    assert not result.is_error, result.output

    body = _agent("different", "after").model_dump(mode="json")
    result = await system_toolset.call(
        tool_name="update_agent", arguments={"id": "a2", "entity": body}
    )
    assert result.is_error
    assert json.loads(result.output)["type"] == "conflict"


# ===========================================================================
# REST PUT coverage for make_crud_router._update (the regression site).
#
# The handler parses the body as a raw dict and calls model_validate; a
# schema-invalid body must surface as 422 (RequestValidationError), not a
# bare 500. These tests drive the real ASGI app end-to-end.
# ===========================================================================


class _Thing(Identifiable):
    _id_prefix: ClassVar[str] = "thing"
    name: str


class _ThingStorage:
    def __init__(self) -> None:
        self._data: dict[str, _Thing] = {}

    async def get(self, id: str) -> _Thing | None:
        return self._data.get(id)

    async def create(self, entity: _Thing) -> _Thing:
        self._data[entity.id] = entity
        return entity

    async def update(self, entity: _Thing) -> _Thing:
        self._data[entity.id] = entity
        return entity

    async def delete(self, id: str) -> None:
        self._data.pop(id, None)


# Module-level singleton so the FastAPI dependency can reach the fixture's
# storage; reset per test by the fixture below.
_THING_STORAGE: _ThingStorage | None = None


def _get_thing_storage() -> _ThingStorage:
    assert _THING_STORAGE is not None
    return _THING_STORAGE


@pytest_asyncio.fixture
async def things_client() -> AsyncIterator[httpx.AsyncClient]:
    global _THING_STORAGE  # noqa: PLW0603

    _THING_STORAGE = _ThingStorage()
    _THING_STORAGE._data["t1"] = _Thing(id="t1", name="before")

    router = make_crud_router(
        model_cls=_Thing,
        storage_dep=_get_thing_storage,
        plural="things",
        tag="things",
    )

    app = FastAPI()
    register_error_handlers(app)
    app.include_router(router)

    async with httpx.AsyncClient(
        transport=ASGITransport(app=app), base_url="http://test"
    ) as client:
        yield client

    _THING_STORAGE = None


@pytest.mark.asyncio
async def test_rest_update_omitted_id_uses_path_id(
    things_client: httpx.AsyncClient,
) -> None:
    resp = await things_client.put("/things/t1", json={"name": "after"})
    assert resp.status_code == 200, resp.text
    body = resp.json()
    assert body["id"] == "t1"
    assert body["name"] == "after"
    assert _THING_STORAGE is not None
    stored = _THING_STORAGE._data["t1"]
    assert stored.id == "t1"
    assert stored.name == "after"


@pytest.mark.asyncio
async def test_rest_update_invalid_body_returns_422(
    things_client: httpx.AsyncClient,
) -> None:
    # `name` declared str; a nested object value fails validation and must
    # render as 422 (RequestValidationError), NOT a bare 500. This is the
    # regression guard for the raw-pydantic-ValidationError fix.
    resp = await things_client.put(
        "/things/t1", json={"name": {"nope": True}}
    )
    assert resp.status_code == 422, resp.text


@pytest.mark.asyncio
async def test_rest_update_mismatched_id_returns_409(
    things_client: httpx.AsyncClient,
) -> None:
    resp = await things_client.put(
        "/things/t1", json={"id": "different", "name": "x"}
    )
    assert resp.status_code == 409, resp.text


# ===========================================================================
# Cross-layer regression: internal create-without-id autogenerates a
# type-prefixed id at the model chokepoint; a supplied id is preserved; and
# the model no longer marks ``id`` required (so the create tool's args_schema
# derives an optional ``id``).
# ===========================================================================


def _agent_body(description: str) -> dict[str, Any]:
    """A valid Agent body WITHOUT an id, mirroring ``_agent`` above."""
    return {
        "description": description,
        "model": AgentModel(
            provider_id="anthropic-1", model_name="claude-sonnet-4-6"
        ).model_dump(mode="json"),
        "temperature": 0.0,
        "tools": [],
        "system_prompt": ["you are a test"],
    }


@pytest.mark.asyncio
async def test_create_without_id_autogenerates(system_toolset) -> None:
    result = await system_toolset.call(
        tool_name="create_agent",
        arguments={"entity": _agent_body("no id supplied")},
    )
    assert not result.is_error, result.output

    new_id = json.loads(result.output)["id"]
    assert re.fullmatch(r"agent-[0-9a-f]{12}", new_id), new_id

    # Retrievable from storage by the autogenerated id.
    result = await system_toolset.call(
        tool_name="get_agent", arguments={"id": new_id}
    )
    assert not result.is_error, result.output
    assert json.loads(result.output)["description"] == "no id supplied"


@pytest.mark.asyncio
async def test_create_with_supplied_id_is_kept(system_toolset) -> None:
    body = _agent_body("explicit id")
    body["id"] = "my-agent"
    result = await system_toolset.call(
        tool_name="create_agent", arguments={"entity": body}
    )
    assert not result.is_error, result.output
    assert json.loads(result.output)["id"] == "my-agent"

    result = await system_toolset.call(
        tool_name="get_agent", arguments={"id": "my-agent"}
    )
    assert not result.is_error, result.output
    assert json.loads(result.output)["id"] == "my-agent"


def test_create_tool_schema_marks_id_optional() -> None:
    # Robust, harness-free assertion: the create tool's wrapper args_schema
    # derives from the model schema, which no longer requires ``id``.
    schema = Agent.model_json_schema()
    assert "id" not in schema.get("required", [])
