"""Regression guard: model autogen must NOT fire for bundle-supplied ids.

Harness install resolves entity ids to ``{slug}__{template_name}`` and
constructs the model with that explicit id. The optional-id autogen branch
in :class:`primer.model.common.Identifiable` must leave such an explicit id
untouched (otherwise harness-managed rows would get random ``<prefix>-<hex>``
ids and break id-stable sync/uninstall). When no id is supplied, autogen
fires with the type prefix.
"""

from __future__ import annotations

import re

from primer.model.provider import Toolset, ToolsetProviderType


def test_explicit_underscore_id_is_preserved_not_autogenerated() -> None:
    ts = Toolset.model_validate({"id": "acme__ts", "provider": "internal"})
    assert ts.id == "acme__ts"  # NOT a toolset-<hex> autogen


def test_omitted_id_autogenerates_toolset_prefix() -> None:
    ts = Toolset(provider=ToolsetProviderType.INTERNAL)
    assert re.fullmatch(r"toolset-[0-9a-f]{12}", ts.id)
