"""Regenerate docs/tests/COMPLETION-MATRIX.md from SMK ids + @smk markers.

Static scan (no test import side effects): SMK ids come from docs/tests
headings; coverage comes from ``smk("SMK-...", status=...)`` calls in the test
tree. Marker present -> full|partial; absent -> none.
"""
from __future__ import annotations

import ast
import re
import sys
from pathlib import Path

_ID_RE = re.compile(r"^#{2,3}\s+(SMK-[A-Z]+-\d+):", re.MULTILINE)
_SMK_ID = re.compile(r"^SMK-[A-Z]+-\d+$")


def scan_smk_ids(docs_dir: Path) -> list[str]:
    ids: list[str] = []
    for md in sorted(Path(docs_dir).rglob("*.md")):
        ids += _ID_RE.findall(md.read_text(encoding="utf-8"))
    return sorted(set(ids))


def _marker_from_call(node: ast.Call) -> tuple[list[str], str]:
    """Pull SMK ids + status from a ``smk(...)`` call node."""
    ids = [
        a.value
        for a in node.args
        if isinstance(a, ast.Constant)
        and isinstance(a.value, str)
        and _SMK_ID.match(a.value)
    ]
    status = "full"
    for kw in node.keywords:
        if kw.arg == "status" and isinstance(kw.value, ast.Constant):
            status = str(kw.value.value)
    return ids, status


def scan_markers(tests_dir: Path) -> dict[str, str]:
    """Find ``@smk("SMK-...", status=...)`` markers across the test tree.

    Uses an AST walk rather than a text regex so that marker-shaped *string
    literals* (e.g. the example markers inside this script's own unit test)
    are NOT counted -- only real ``smk(...)`` call nodes are.
    """
    found: dict[str, str] = {}
    for py in sorted(Path(tests_dir).rglob("test_*.py")):
        try:
            tree = ast.parse(py.read_text(encoding="utf-8"))
        except SyntaxError:
            continue
        for node in ast.walk(tree):
            if not isinstance(node, ast.Call):
                continue
            fn = node.func
            name = (
                fn.id if isinstance(fn, ast.Name)
                else fn.attr if isinstance(fn, ast.Attribute)
                else None
            )
            if name != "smk":
                continue
            ids, status = _marker_from_call(node)
            for raw in ids:
                # full wins over partial if any test fully covers the id
                if found.get(raw) != "full":
                    found[raw] = status
    return found


def classify(ids: list[str], markers: dict[str, str]) -> dict[str, str]:
    return {i: markers.get(i, "none") for i in ids}


def render(rows: dict[str, str]) -> str:
    counts = {"full": 0, "partial": 0, "none": 0}
    for v in rows.values():
        counts[v] += 1
    lines = [
        "# Smoke-test completion matrix (generated)",
        "",
        "Regenerated by scripts/tests/coverage_matrix.py from docs/tests SMK ids",
        "and @smk markers in the test tree. Do not edit by hand.",
        "",
        f"FULL {counts['full']} | PARTIAL {counts['partial']} | NONE {counts['none']} "
        f"| total {len(rows)}",
        "",
        "| Test | Status |",
        "| --- | --- |",
    ]
    for i in sorted(rows):
        lines.append(f"| {i} | {rows[i].upper()} |")
    return "\n".join(lines) + "\n"


def main() -> int:
    repo = Path(__file__).resolve().parents[2]
    rows = classify(
        scan_smk_ids(repo / "docs" / "tests"),
        scan_markers(repo / "tests"),
    )
    (repo / "docs" / "tests" / "COMPLETION-MATRIX.md").write_text(
        render(rows), encoding="utf-8"
    )
    sys.stdout.write(render(rows))
    return 0


if __name__ == "__main__":
    sys.exit(main())
