"""Regenerate docs/tests/COMPLETION-MATRIX.md from SMK ids + @smk markers.

Static scan (no test import side effects): SMK ids come from docs/tests
headings; coverage comes from ``smk("SMK-...", status=...)`` calls in the test
tree. Marker present -> full|partial; absent -> none.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

_ID_RE = re.compile(r"^#{2,3}\s+(SMK-[A-Z]+-\d+):", re.MULTILINE)
_CALL_RE = re.compile(r"smk\(([^)]*)\)")
_ID_IN_ARGS = re.compile(r"\"(SMK-[A-Z]+-\d+)\"")
_STATUS_IN_ARGS = re.compile(r"status\s*=\s*\"(\w+)\"")


def scan_smk_ids(docs_dir: Path) -> list[str]:
    ids: list[str] = []
    for md in sorted(Path(docs_dir).rglob("*.md")):
        ids += _ID_RE.findall(md.read_text(encoding="utf-8"))
    return sorted(set(ids))


def scan_markers(tests_dir: Path) -> dict[str, str]:
    found: dict[str, str] = {}
    for py in sorted(Path(tests_dir).rglob("test_*.py")):
        text = py.read_text(encoding="utf-8")
        for m in _CALL_RE.finditer(text):
            args = m.group(1)
            ids = _ID_IN_ARGS.findall(args)
            if not ids:
                continue
            status_m = _STATUS_IN_ARGS.search(args)
            status = status_m.group(1) if status_m else "full"
            for raw in ids:
                # full wins over partial if any test fully covers the id
                if found.get(raw) != "full":
                    found[raw] = status
    return found


def classify(ids: list[str], markers: dict[str, str]) -> dict[str, str]:
    return {i: markers.get(i, "none") for i in ids}


def render(rows: dict[str, str]) -> str:
    counts = {"full": 0, "partial": 0, "none": 0}
    for v in rows.values():
        counts[v] += 1
    lines = [
        "# Smoke-test completion matrix (generated)",
        "",
        "Regenerated by scripts/tests/coverage_matrix.py from docs/tests SMK ids",
        "and @smk markers in the test tree. Do not edit by hand.",
        "",
        f"FULL {counts['full']} | PARTIAL {counts['partial']} | NONE {counts['none']} "
        f"| total {len(rows)}",
        "",
        "| Test | Status |",
        "| --- | --- |",
    ]
    for i in sorted(rows):
        lines.append(f"| {i} | {rows[i].upper()} |")
    return "\n".join(lines) + "\n"


def main() -> int:
    repo = Path(__file__).resolve().parents[2]
    rows = classify(
        scan_smk_ids(repo / "docs" / "tests"),
        scan_markers(repo / "tests"),
    )
    (repo / "docs" / "tests" / "COMPLETION-MATRIX.md").write_text(
        render(rows), encoding="utf-8"
    )
    sys.stdout.write(render(rows))
    return 0


if __name__ == "__main__":
    sys.exit(main())
