"""OIDC SSO models (Layer 2, Task 1) — ``OidcProvider`` + ``UserIdentity``."""

from __future__ import annotations

from datetime import datetime, timezone

from primer.model.common import dump_for_storage
from primer.model.oidc import OidcProvider, UserIdentity


def _provider_kwargs(**overrides):
    kwargs = dict(
        name="Okta",
        discovery_url="https://x/.well-known/openid-configuration",
        client_id="c",
        client_secret="s",
    )
    kwargs.update(overrides)
    return kwargs


class TestOidcProvider:
    def test_id_autogenerated_with_prefix(self) -> None:
        p = OidcProvider(**_provider_kwargs())
        assert p.id is not None
        assert p.id.startswith("oidc-provider-")

    def test_enabled_defaults_true(self) -> None:
        p = OidcProvider(**_provider_kwargs())
        assert p.enabled is True

    def test_scopes_default_openid_email_profile(self) -> None:
        p = OidcProvider(**_provider_kwargs())
        assert p.scopes == ["openid", "email", "profile"]

    def test_client_secret_redacted_in_model_dump_json(self) -> None:
        p = OidcProvider(**_provider_kwargs())
        dumped = p.model_dump(mode="json")
        assert dumped["client_secret"] == "**********"

    def test_dump_for_storage_preserves_real_secret(self) -> None:
        p = OidcProvider(**_provider_kwargs())
        dumped = dump_for_storage(p)
        assert dumped["client_secret"] == "s"


class TestUserIdentity:
    def test_id_autogenerated_with_prefix(self) -> None:
        ui = UserIdentity(
            user_id="user-1",
            provider_id="oidc-provider-1",
            subject="sub-1",
            created_at=datetime(2024, 1, 1, tzinfo=timezone.utc),
        )
        assert ui.id is not None
        assert ui.id.startswith("user-identity-")
