"""One-shot developer-docs consolidation verifier.

Workflow:
1. Run the hygiene test suite (tests/docs/).
2. If tests pass, roll up planned-but-not-built items from every triage
   card under docs/dev/_work/triage/ into docs/dev/deferred-from-specs.md.
3. Remove docs/dev/_work/ so the scratch state does not leak into the
   final commit.

If tests fail, the script exits non-zero without performing side-effects.

Run as a script: ``uv run python scripts/docs_verifier.py``.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DOCS_DEV = REPO / "docs" / "dev"
WORK_DIR = DOCS_DEV / "_work"
TRIAGE_DIR = WORK_DIR / "triage"
DEFERRED_PATH = DOCS_DEV / "deferred-from-specs.md"


def run_hygiene_tests() -> int:
    """Run the pytest hygiene suite and return the exit code."""
    print("Running hygiene tests...", flush=True)
    result = subprocess.run(
        ["uv", "run", "pytest", "tests/docs/", "-v"],
        cwd=REPO,
    )
    return result.returncode


def generate_deferred_rollup() -> None:
    """Aggregate `spec_says_code_lacks` entries from every triage card
    into a single markdown file grouped by spec date."""
    if not TRIAGE_DIR.exists():
        print(
            f"WARN: {TRIAGE_DIR} does not exist; skipping deferred roll-up.",
            file=sys.stderr,
        )
        return
    by_date: dict[str, list[tuple[str, str, str]]] = defaultdict(list)
    for card_path in sorted(TRIAGE_DIR.glob("*.json")):
        try:
            card = json.loads(card_path.read_text())
        except json.JSONDecodeError:
            print(f"WARN: skipping malformed {card_path.name}", file=sys.stderr)
            continue
        items = card.get("spec_says_code_lacks") or []
        if not items:
            continue
        title = card.get("spec_title", card_path.stem)
        spec_path = card.get("spec_path", "")
        date = card.get("spec_date", "0000-00-00")
        for item in items:
            by_date[date].append((title, spec_path, item))

    lines = [
        "# Deferred from Specs",
        "",
        "Planned-but-not-built items rolled up from the triage cards that",
        "fed the consolidated developer docs. Entries are grouped by the",
        "originating spec date.",
        "",
        "This file is regenerated by `scripts/docs_verifier.py`. Manual",
        "edits will be overwritten on the next consolidation run.",
        "",
    ]
    if not by_date:
        lines.append(
            "No deferred items at the time this file was generated."
        )
    else:
        for date in sorted(by_date.keys()):
            lines.append(f"## {date}")
            lines.append("")
            by_title: dict[str, list[tuple[str, str]]] = defaultdict(list)
            for title, spec_path, item in by_date[date]:
                by_title[title].append((spec_path, item))
            for title in sorted(by_title.keys()):
                lines.append(f"### {title}")
                lines.append("")
                lines.append(f"Source: `{by_title[title][0][0]}`")
                lines.append("")
                for _, item in by_title[title]:
                    lines.append(f"- {item}")
                lines.append("")

    DEFERRED_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {DEFERRED_PATH.relative_to(REPO)}", flush=True)


def remove_work_dir() -> None:
    """Remove the scratch directory so it does not leak into the commit."""
    if WORK_DIR.exists():
        shutil.rmtree(WORK_DIR)
        print(f"Removed {WORK_DIR.relative_to(REPO)}", flush=True)


def main() -> int:
    rc = run_hygiene_tests()
    if rc != 0:
        print(
            "\nHygiene tests failed. Refusing to finalize the consolidation.\n"
            "Fix the failures and re-run scripts/docs_verifier.py.",
            file=sys.stderr,
        )
        return rc
    print("\nHygiene tests passed. Performing side-effects...", flush=True)
    generate_deferred_rollup()
    remove_work_dir()
    print(
        "\nVerification complete. docs/dev/ is ready for commit.",
        flush=True,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
