"""Stored binary artifact (chat media bytes).

An ``Artifact`` row holds the raw bytes of one piece of chat media (an image,
document, or audio clip) keyed by an autogenerated id. Chat media parts
reference an artifact by ``artifact_id`` instead of carrying the bytes inline
in the ``ChatMessage`` row; the bytes are rehydrated at turn time and at
outbound-relay time. The default :class:`primer.artifact.db.DbArtifactStorage`
persists these rows through the platform StorageProvider; alternate
``ArtifactStorage`` backends (filesystem/S3) need not use this model.
"""

from __future__ import annotations

from typing import Annotated, ClassVar

from pydantic import BeforeValidator, Field, PlainSerializer

from primer.model.chat import _decode_b64_if_str, _encode_b64_for_json
from primer.model.common import Identifiable


class Artifact(Identifiable):
    """One stored binary blob of chat media."""

    _id_prefix: ClassVar[str] = "artifact"

    mime_type: str = Field(
        ...,
        description="MIME type of the bytes (e.g. 'image/png', 'application/pdf').",
    )
    filename: str | None = Field(
        default=None,
        description="Original filename, when the source provided one.",
    )
    size: int = Field(
        ...,
        description="Size of ``data`` in bytes (after any compression).",
    )
    data: Annotated[
        bytes,
        BeforeValidator(_decode_b64_if_str),
        PlainSerializer(_encode_b64_for_json, return_type=str, when_used="json"),
    ] = Field(
        ...,
        description="Raw artifact bytes. Pydantic accepts base64-encoded strings.",
    )


__all__ = ["Artifact"]
