"""Entities for the channels feature."""

from __future__ import annotations

from enum import Enum
from typing import Annotated, ClassVar, Literal, Union

from pydantic import BaseModel, ConfigDict, Field, SecretStr, field_validator, model_validator

from primer.model.common import Identifiable


class ChannelProviderType(str, Enum):
    SLACK = "slack"
    TELEGRAM = "telegram"
    DISCORD = "discord"


class SlackChannelProviderConfig(BaseModel):
    """Credentials for one Slack workspace (Slack-team)."""

    app_token: SecretStr = Field(
        ...,
        description=(
            "App-level token (xapp-…) required for Socket Mode. "
            "Generated in the Slack app's Basic Information panel."
        ),
    )
    bot_token: SecretStr = Field(
        ...,
        description=(
            "Bot OAuth token (xoxb-…) used for chat.postMessage, "
            "conversations.history, etc."
        ),
    )
    signing_secret: SecretStr | None = Field(
        default=None,
        description=(
            "Optional. Unused in Socket Mode (signing only matters "
            "for HTTP event delivery)."
        ),
    )

    # Per-field validators so loc tuples carry the field name
    # (loc=("body","config","app_token") etc.), letting the UI modal
    # render an inline error under the offending field. A combined
    # @model_validator would flatten the loc to ("body",) and the
    # modal's per-field error lookup would miss it entirely.
    @field_validator("app_token")
    @classmethod
    def _validate_app_token(cls, v: SecretStr) -> SecretStr:
        if not v.get_secret_value().startswith("xapp-"):
            raise ValueError(
                "app_token must start with 'xapp-' (Slack app-level token)"
            )
        return v

    @field_validator("bot_token")
    @classmethod
    def _validate_bot_token(cls, v: SecretStr) -> SecretStr:
        if not v.get_secret_value().startswith("xoxb-"):
            raise ValueError(
                "bot_token must start with 'xoxb-' (Slack bot token)"
            )
        return v


class TelegramChannelProviderConfig(BaseModel):
    """One Telegram bot token + polling knob."""

    bot_token: SecretStr = Field(
        ...,
        description=(
            "Telegram bot token in '123456:ABCDEF…' shape "
            "(generated by @BotFather)."
        ),
    )
    poll_timeout_seconds: int = Field(
        default=25, ge=1, le=60,
        description=(
            "Long-poll timeout per getUpdates call. Telegram caps "
            "at 50; 25 balances latency vs connection churn."
        ),
    )

    @field_validator("bot_token")
    @classmethod
    def _validate_bot_token(cls, v: SecretStr) -> SecretStr:
        tok = v.get_secret_value()
        if ":" not in tok or len(tok) < 20:
            raise ValueError(
                "bot_token must be in the '123456:ABCDEF...' shape"
            )
        return v


class DiscordChannelProviderConfig(BaseModel):
    """One Discord bot token + intent toggle."""

    bot_token: SecretStr = Field(
        ...,
        description=(
            "Discord bot token from the Developer Portal. Do NOT "
            "include the 'Bot ' prefix; the adapter adds it."
        ),
    )
    enable_dms: bool = Field(
        default=True,
        description=(
            "Request dm_messages intent so the bot can read DM "
            "channels. Turn off for guild-only deployments."
        ),
    )

    @field_validator("bot_token")
    @classmethod
    def _validate_bot_token(cls, v: SecretStr) -> SecretStr:
        tok = v.get_secret_value()
        if not tok or len(tok) < 30:
            raise ValueError(
                "bot_token must be the Developer Portal bot token "
                "(>=30 chars); do NOT include the 'Bot ' prefix"
            )
        return v


ChannelProviderConfig = Annotated[
    SlackChannelProviderConfig | TelegramChannelProviderConfig | DiscordChannelProviderConfig,
    Field(description="Platform-specific config; must match parent provider."),
]


class ChannelProvider(Identifiable):
    """A configured messaging-platform credential set."""

    _id_prefix: ClassVar[str] = "channel-provider"

    provider: ChannelProviderType = Field(...)
    config: ChannelProviderConfig = Field(...)

    @model_validator(mode="before")
    @classmethod
    def _coerce_config_type(cls, values):
        """When ``config`` is a plain dict, construct the right config type.

        Pydantic union parsing always picks the first matching variant
        (``SlackChannelProviderConfig`` for ``{}``) regardless of the
        ``provider`` value. We intercept *before* field parsing so we
        can inject the correct concrete type from the provider name.
        """
        if not isinstance(values, dict):
            return values
        provider_val = values.get("provider")
        config_val = values.get("config")
        if provider_val is None or not isinstance(config_val, dict):
            return values
        # Resolve the provider string (may be an enum value or string).
        pv = provider_val.value if hasattr(provider_val, "value") else str(provider_val)
        cls_map = {
            "slack": SlackChannelProviderConfig,
            "telegram": TelegramChannelProviderConfig,
            "discord": DiscordChannelProviderConfig,
        }
        config_cls = cls_map.get(pv)
        if config_cls is not None:
            values = dict(values)
            values["config"] = config_cls(**config_val)
        return values

    @model_validator(mode="after")
    def _validate_config_matches(self) -> "ChannelProvider":
        match self.provider:
            case ChannelProviderType.SLACK:
                if not isinstance(self.config, SlackChannelProviderConfig):
                    raise ValueError(
                        "provider='slack' requires a SlackChannelProviderConfig"
                    )
            case ChannelProviderType.TELEGRAM:
                if not isinstance(self.config, TelegramChannelProviderConfig):
                    raise ValueError(
                        "provider='telegram' requires a TelegramChannelProviderConfig"
                    )
            case ChannelProviderType.DISCORD:
                if not isinstance(self.config, DiscordChannelProviderConfig):
                    raise ValueError(
                        "provider='discord' requires a DiscordChannelProviderConfig"
                    )
        return self


class ChatConfig(BaseModel):
    """Chat-surface settings for a channel room."""

    model_config = ConfigDict(extra="forbid")

    enabled: bool = Field(
        default=False,
        description="Whether channel-initiated chats are allowed on this room.",
    )
    default_agent: str | None = Field(
        default=None,
        description="Agent each new chat starts with; required when enabled.",
    )
    allow_agent_switch: bool = Field(
        default=False,
        description=(
            "Whether users may switch a chat's agent via /agent. Off by "
            "default so an operator who enables chats does not implicitly let "
            "anyone change the agent. ``allowed_agents`` only applies when this "
            "is on."
        ),
    )
    allowed_agents: list[str] = Field(
        default_factory=list,
        description=(
            "When agent switching is allowed, restricts /agent to these agents; "
            "[] = any agent. Ignored when allow_agent_switch is off."
        ),
    )
    relay_mode: Literal["final", "all"] = Field(
        default="final",
        description="Outbound chat verbosity.",
    )

    @model_validator(mode="after")
    def _validate_chat_constraints(self) -> "ChatConfig":
        if self.allowed_agents and self.default_agent and self.default_agent not in self.allowed_agents:
            raise ValueError(
                "default_agent must be one of allowed_agents when allowed_agents is non-empty"
            )
        if self.enabled and not self.default_agent:
            raise ValueError("default_agent is required when chats are enabled")
        return self


class SlackChannelConfig(BaseModel):
    """Per-room config for a Slack channel."""

    model_config = ConfigDict(extra="forbid")

    chats: ChatConfig = Field(default_factory=ChatConfig)


class DiscordChannelConfig(BaseModel):
    """Per-room config for a Discord channel."""

    model_config = ConfigDict(extra="forbid")

    chats: ChatConfig = Field(default_factory=ChatConfig)


class TelegramChannelConfig(BaseModel):
    """Per-room config for a Telegram channel."""

    model_config = ConfigDict(extra="forbid")

    chats: ChatConfig = Field(default_factory=ChatConfig)


class Channel(Identifiable):
    """One conversational target within a ChannelProvider."""

    _id_prefix: ClassVar[str] = "channel"

    provider_id: str = Field(..., description="FK to ChannelProvider.id.")
    provider: ChannelProviderType = Field(..., description="Platform; discriminates config.")
    external_id: str = Field(..., description="Platform room/chat id.")
    label: str | None = Field(default=None, max_length=200)
    config: SlackChannelConfig | DiscordChannelConfig | TelegramChannelConfig = Field(
        default=None,
        description="Provider-specific config; must match provider.",
    )

    @model_validator(mode="before")
    @classmethod
    def _coerce_config_type(cls, values):
        """When ``config`` is a plain dict (or absent), construct the correct concrete type.

        Pydantic union parsing always picks the first matching variant
        (``SlackChannelConfig`` for ``{}``) regardless of the ``provider`` value.
        We intercept *before* field parsing so we can inject the correct concrete
        type from the provider name. When ``config`` is absent (None or missing),
        we default to ``{}`` and build the right empty config.
        """
        if not isinstance(values, dict):
            return values
        provider_val = values.get("provider")
        if provider_val is None:
            return values
        pv = provider_val.value if hasattr(provider_val, "value") else str(provider_val)
        cls_map = {
            "slack": SlackChannelConfig,
            "telegram": TelegramChannelConfig,
            "discord": DiscordChannelConfig,
        }
        config_cls = cls_map.get(pv)
        if config_cls is None:
            return values
        config_val = values.get("config")
        if config_val is None or isinstance(config_val, dict):
            values = dict(values)
            values["config"] = config_cls(**(config_val or {}))
        return values

    @model_validator(mode="after")
    def _config_matches_provider(self) -> "Channel":
        expected = {
            ChannelProviderType.SLACK: SlackChannelConfig,
            ChannelProviderType.DISCORD: DiscordChannelConfig,
            ChannelProviderType.TELEGRAM: TelegramChannelConfig,
        }[self.provider]
        if not isinstance(self.config, expected):
            raise ValueError(f"provider={self.provider.value!r} requires {expected.__name__}")
        return self


__all__ = [
    "Channel",
    "ChannelProvider",
    "ChannelProviderConfig",
    "ChannelProviderType",
    "ChatConfig",
    "DiscordChannelConfig",
    "DiscordChannelProviderConfig",
    "SlackChannelConfig",
    "SlackChannelProviderConfig",
    "TelegramChannelConfig",
    "TelegramChannelProviderConfig",
]
