"""RFC 7807 problem-details Pydantic model.

Lives in the model layer so domain modules (e.g. ``primer.model.turn_log``)
can use it as a field type without reaching upward into ``primer.api``.

``primer.api.errors`` re-exports this same class so existing
``from primer.api.errors import ProblemDetails`` callers keep working.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class ProblemDetails(BaseModel):
    """RFC 7807 problem details object."""

    type: str = Field(
        ...,
        description="URI reference identifying the problem type.",
    )
    title: str = Field(
        ...,
        description="Short, human-readable summary of the problem type.",
    )
    status: int = Field(
        ...,
        description="HTTP status code generated by the origin server.",
    )
    detail: str = Field(
        ...,
        description="Human-readable explanation specific to this occurrence.",
    )
    instance: str | None = Field(
        default=None,
        description=(
            "URI reference identifying the specific occurrence (request path)."
        ),
    )
    extensions: dict[str, Any] | None = Field(
        default=None,
        description="Extension members per RFC 7807 §3.2.",
    )


__all__ = ["ProblemDetails"]
