"""ToolCallTask — scheduling state for one independently-claimable tool call.

Phase 3 stage 7a (docs/superpowers/2026-08-29-phase3-execution-topology-design.md,
user-approved; ground-truth remap in
docs/superpowers/2026-09-03-phase3-7a-ground-truth-remap.md). Every tool call
in a batch becomes its own claimable unit instead of executing sequentially
in-process, so parallel batches parallelize by worker availability and a
single gated call no longer blocks its siblings.

This row is SCHEDULING STATE ONLY (01a0518b Q1, resolved: ref, not inline).
The durable ``TOOL_CALL``/``TOOL_RESULT`` records in messages.jsonl remain
the transcript truth; this row never carries the tool's own execution
arguments or results inline, only enough to answer "is this done, and
what's its own lifecycle state" for the claim engine's eligibility
filter and the session's last-task-releases-re-arms-the-turn
bookkeeping. ``gate_state`` (below) is a narrow, ruling-approved
exception, not the row's general payload — see its own docstring.
"""

from __future__ import annotations

from datetime import datetime
from enum import StrEnum
from typing import Any

from pydantic import Field

from primer.model.common import Identifiable


class ToolCallTaskState(StrEnum):
    """Mirrors the design doc's own enum exactly: queued|gated|running|done|failed."""

    QUEUED = "queued"
    GATED = "gated"
    RUNNING = "running"
    DONE = "done"
    FAILED = "failed"


class ToolCallTask(Identifiable):
    """One independently-claimable tool call within a session turn.

    ``id`` is the dispatch-layer scoped tool-call id
    (``node:tool:turn_no:seq``), minted at the SAME dispatch seam that
    creates this row and that mints the durable ``TOOL_CALL`` record's own
    id (see the ground-truth remap's "scoped tool-call id does not reach
    the dispatch layer" finding — this row's id and the transcript
    record's id MUST be the same string for the two to be joinable). NOT
    autogenerated (no ``_id_prefix``): the dispatch seam always supplies
    it explicitly, matching the design's "id = tool_call_id".
    """

    session_id: str = Field(..., min_length=1)
    turn_no: int = Field(..., ge=0)
    tool_name: str = Field(..., min_length=1)
    state: ToolCallTaskState = ToolCallTaskState.QUEUED

    # The durable TOOL_CALL record's own seq (primer.model.workspace_session.
    # SessionMessageRecord.seq) — a POINTER, not a copy, so Q1's ref-only
    # framing stays intact. REQUIRED (not optional): this is the field that
    # ENCODES the ordering invariant the whole design depends on. You
    # cannot know a record's seq until AFTER WorkspaceMessageWriter.append
    # durably writes it — so a ToolCallTask can only ever be CONSTRUCTED
    # with a real record_seq once its TOOL_CALL record already exists in
    # messages.jsonl. That ordering (record written, THEN task becomes
    # claimable) is exactly what a claim-based worker needs to be true: it
    # must never be able to claim a task whose TOOL_CALL record isn't
    # durable yet. The lookup helper that reads a task's arguments back
    # (primer.claim.tool_call_lookup, once it lands) seeks directly to
    # this seq and verifies the record's own id == this row's id, failing
    # loudly on any mismatch rather than falling back to a scan — a
    # mismatch means this invariant broke somewhere upstream, which is a
    # bug worth surfacing, not papering over.
    record_seq: int = Field(..., ge=1)

    # Set only while state == GATED (approval-required or a yielding tool
    # mid-execution) — the gate's own event_key, so the resume path knows
    # which wake event to wait for. Mirrors WorkspaceSession.parked_event_key
    # in spirit, task-scoped instead of session-scoped so one gated call in
    # a batch does not block its siblings (the design's own motivating bug).
    gate_event_key: str | None = None
    gate_until: datetime | None = None

    # Set only while state == GATED - the SAME parked-state blob shape
    # session/graph parks already carry (yielded.resume_metadata.
    # original_call + policy_id/approval_type/gate_reason - see
    # primer.agent.approval_record.record_from_parked_blob, which reads
    # exactly this shape and is reused unmodified for the task-granular
    # ToolApprovalRecord write ruling 3's rider requires at resume).
    # This is the one narrow exception to "scheduling state only" (Q1):
    # ruling 3 (01a0518b) - task row stays pointer-only for the FINISHED
    # transcript truth (TOOL_CALL/TOOL_RESULT records), but a gate's live
    # payload has no other durable home at task granularity (unlike a
    # session park, which already had parked_state as its established
    # home; a bare-new ToolCallTask has nothing else to point at).
    # NOT cleared at resume (GATED -> QUEUED, see
    # primer.claim.tool_call_resume.durably_mark_tool_call_task_resumable):
    # the resume decision itself gets stashed in here too
    # (resume_event_payload/resume_event_key, mirroring
    # WorkspaceSession.parked_state's own resume-payload convention) so
    # the re-claiming worker has something to read the decision from.
    # Cleared to None only once actually consumed - on a terminal
    # release (DONE/FAILED) or a transient-failure requeue back to
    # QUEUED, see ToolCallClaimAdapter.on_release.
    gate_state: dict[str, Any] | None = None

    # Set only on a terminal (state in {DONE, FAILED}) release when the
    # underlying tool call itself failed - independent of whether the ROW's
    # own scheduling lifecycle completed successfully (it always does,
    # once terminal; "failed" describes the tool call, not the task
    # bookkeeping). The durable TOOL_RESULT record is the actual error
    # detail; this is a cheap, queryable summary only.
    last_error: str | None = None

    # Set only on a terminal (DONE/FAILED) release - the claim worker's
    # full tool-execution result (primer.model.chat.ToolResultPart's own
    # shape: output/error/metadata), NOT yet written as a durable
    # TOOL_RESULT record. Ruling (01a0518b, "same philosophy as
    # gate_state"): the SINGLE in-process session-log writer + its
    # in-memory seq counter is the shared, working invariant this design
    # must not touch (a claim worker allocating its own atomic seq would
    # still race the still-active original turn's stale in-memory
    # counter) - so the claim worker writes ONLY here + publishes the
    # tick, and the task-resume-coordinator (not yet built) is what
    # actually materializes the durable TOOL_RESULT record, in-process,
    # under the session log's existing single-writer lock, when the
    # parked turn resumes. Cleared to None once the resume coordinator
    # has consumed it into a durable record - this field is a mailbox,
    # not a second copy of the transcript.
    result_state: dict[str, Any] | None = None

    created_at: datetime
    started_at: datetime | None = None
    finished_at: datetime | None = None


__all__ = ["ToolCallTask", "ToolCallTaskState"]
