"""ToolCallTask — scheduling state for one independently-claimable tool call.

Phase 3 stage 7a (docs/superpowers/2026-08-29-phase3-execution-topology-design.md,
user-approved; ground-truth remap in
docs/superpowers/2026-09-03-phase3-7a-ground-truth-remap.md). Every tool call
in a batch becomes its own claimable unit instead of executing sequentially
in-process, so parallel batches parallelize by worker availability and a
single gated call no longer blocks its siblings.

This row is SCHEDULING STATE ONLY (01a0518b Q1, resolved: ref, not inline).
The durable ``TOOL_CALL``/``TOOL_RESULT`` records in messages.jsonl remain
the transcript truth; this row never carries tool arguments or results
inline, only enough to answer "is this done, and what's its own lifecycle
state" for the claim engine's eligibility filter and the session's
last-task-releases-re-arms-the-turn bookkeeping.
"""

from __future__ import annotations

from datetime import datetime
from enum import StrEnum

from pydantic import Field

from primer.model.common import Identifiable


class ToolCallTaskState(StrEnum):
    """Mirrors the design doc's own enum exactly: queued|gated|running|done|failed."""

    QUEUED = "queued"
    GATED = "gated"
    RUNNING = "running"
    DONE = "done"
    FAILED = "failed"


class ToolCallTask(Identifiable):
    """One independently-claimable tool call within a session turn.

    ``id`` is the dispatch-layer scoped tool-call id
    (``node:tool:turn_no:seq``), minted at the SAME dispatch seam that
    creates this row and that mints the durable ``TOOL_CALL`` record's own
    id (see the ground-truth remap's "scoped tool-call id does not reach
    the dispatch layer" finding — this row's id and the transcript
    record's id MUST be the same string for the two to be joinable). NOT
    autogenerated (no ``_id_prefix``): the dispatch seam always supplies
    it explicitly, matching the design's "id = tool_call_id".
    """

    session_id: str = Field(..., min_length=1)
    turn_no: int = Field(..., ge=0)
    tool_name: str = Field(..., min_length=1)
    state: ToolCallTaskState = ToolCallTaskState.QUEUED

    # Set only while state == GATED (approval-required or a yielding tool
    # mid-execution) — the gate's own event_key, so the resume path knows
    # which wake event to wait for. Mirrors WorkspaceSession.parked_event_key
    # in spirit, task-scoped instead of session-scoped so one gated call in
    # a batch does not block its siblings (the design's own motivating bug).
    gate_event_key: str | None = None
    gate_until: datetime | None = None

    # Set only on a terminal (state in {DONE, FAILED}) release when the
    # underlying tool call itself failed - independent of whether the ROW's
    # own scheduling lifecycle completed successfully (it always does,
    # once terminal; "failed" describes the tool call, not the task
    # bookkeeping). The durable TOOL_RESULT record is the actual error
    # detail; this is a cheap, queryable summary only.
    last_error: str | None = None

    created_at: datetime
    started_at: datetime | None = None
    finished_at: datetime | None = None


__all__ = ["ToolCallTask", "ToolCallTaskState"]
