"""Abstract interface for binary artifact storage.

An ``ArtifactStorage`` stores opaque media bytes (chat images / documents /
audio) under an autogenerated id and reads them back. It is the live
implementation behind an :class:`primer.model.provider.ArtifactStorageProvider`
row, resolved per-row by
:class:`primer.api.registries.artifact_storage_registry.ArtifactStorageRegistry`.

The default backend (``DB``) persists an :class:`primer.model.artifact.Artifact`
row through the platform StorageProvider, keeping media bytes out of the
``ChatMessage`` row. Alternate backends (filesystem, S3) implement the same
contract so callers never depend on where the bytes live.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass


@dataclass(frozen=True)
class ArtifactBlob:
    """Bytes plus the metadata needed to forward them to a model or channel."""

    data: bytes
    mime_type: str
    filename: str | None = None


class ArtifactStorage(ABC):
    """Provider-agnostic put/get/delete for opaque media bytes."""

    @abstractmethod
    async def initialize(self) -> None:
        """Open connections / resources. Idempotent."""

    @abstractmethod
    async def put(
        self, *, data: bytes, mime_type: str, filename: str | None = None,
    ) -> str:
        """Store ``data`` and return its autogenerated ``artifact_id``."""

    @abstractmethod
    async def get(self, artifact_id: str) -> ArtifactBlob | None:
        """Return the stored blob, or None when the id is unknown."""

    @abstractmethod
    async def delete(self, artifact_id: str) -> None:
        """Remove ``artifact_id``. No-op when it does not exist."""

    @abstractmethod
    async def aclose(self) -> None:
        """Release connections / resources. Idempotent."""


__all__ = ["ArtifactBlob", "ArtifactStorage"]
